// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD04Y1jF3Pwu-xT_9gII901X-zXwN_GNy4',
    appId: '1:590207086568:web:ac0bee796b2de4cc467e5d',
    messagingSenderId: '590207086568',
    projectId: 'queue-management-f697f',
    authDomain: 'queue-management-f697f.firebaseapp.com',
    storageBucket: 'queue-management-f697f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HhkhEV5rucNFU9CPq4WF8i0OKJ2U7lA',
    appId: '1:590207086568:android:50ce826d367966e5467e5d',
    messagingSenderId: '590207086568',
    projectId: 'queue-management-f697f',
    storageBucket: 'queue-management-f697f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvDJxaKSh1lTJElwzbpyjKK-1epnbMs10',
    appId: '1:590207086568:ios:c703a43eecbc8f23467e5d',
    messagingSenderId: '590207086568',
    projectId: 'queue-management-f697f',
    storageBucket: 'queue-management-f697f.appspot.com',
    iosClientId: '590207086568-7knbb39msk6pau14225gg852c46evp70.apps.googleusercontent.com',
    iosBundleId: 'moreli.com.br.queueManagement',
  );
}
